"""add order_index to badges

Revision ID: 0f4536739682
Revises: 4c3970e4fd18
Create Date: 2026-03-19 15:29:11.904914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4536739682'
down_revision: Union[str, Sequence[str], None] = '4c3970e4fd18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('order_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badges', 'order_index')
    # ### end Alembic commands ###
