"""add description and icon to lesson

Revision ID: 4c3970e4fd18
Revises: b25a1e0cd454
Create Date: 2026-03-19 12:44:15.043566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3970e4fd18'
down_revision: Union[str, Sequence[str], None] = 'b25a1e0cd454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'description')
    op.drop_column('lessons', 'icon')
    # ### end Alembic commands ###
