"""Refactor progress to use run_id and attempt history

Revision ID: a898db699e39
Revises: e9e27fba6720
Create Date: 2026-06-11 13:29:28.717534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a898db699e39'
down_revision: Union[str, Sequence[str], None] = 'e9e27fba6720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_attempt_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('sentence_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_attempt_history_id'), 'sentence_attempt_history', ['id'], unique=False)
    op.create_index(op.f('ix_sentence_attempt_history_lesson_id'), 'sentence_attempt_history', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_sentence_attempt_history_run_id'), 'sentence_attempt_history', ['run_id'], unique=False)
    op.create_index(op.f('ix_sentence_attempt_history_sentence_id'), 'sentence_attempt_history', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_sentence_attempt_history_user_id'), 'sentence_attempt_history', ['user_id'], unique=False)
    op.drop_table('user_sentence_progress')
    op.add_column('user_lesson_progress', sa.Column('current_run_id', sa.String(), nullable=True))
    op.drop_column('user_lesson_progress', 'progress_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lesson_progress', sa.Column('progress_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('user_lesson_progress', 'current_run_id')
    op.create_table('user_sentence_progress',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sentence_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('highest_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('user_sentence_progress_sentence_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_sentence_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'sentence_id', name=op.f('user_sentence_progress_pkey'))
    )
    op.drop_index(op.f('ix_sentence_attempt_history_user_id'), table_name='sentence_attempt_history')
    op.drop_index(op.f('ix_sentence_attempt_history_sentence_id'), table_name='sentence_attempt_history')
    op.drop_index(op.f('ix_sentence_attempt_history_run_id'), table_name='sentence_attempt_history')
    op.drop_index(op.f('ix_sentence_attempt_history_lesson_id'), table_name='sentence_attempt_history')
    op.drop_index(op.f('ix_sentence_attempt_history_id'), table_name='sentence_attempt_history')
    op.drop_table('sentence_attempt_history')
    # ### end Alembic commands ###
