"""remove is_passed from UserSentenceProgress

Revision ID: e9e27fba6720
Revises: 0f4536739682
Create Date: 2026-05-21 16:02:46.601612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e27fba6720'
down_revision: Union[str, Sequence[str], None] = '0f4536739682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sentence_progress', 'is_passed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sentence_progress', sa.Column('is_passed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
